### ISSUE TITLE
VS 2015 compiler error: "expression did not evaluate to a constant"

### ISSUE THREAD

**Issue by nikreiman** [emil-e/rapidcheck#102]
I'm trying to build rapidcheck with VS 2015 (Version 14.0.24720.00 Update 1, to be precise), and am getting compiler errors in `Variant.hpp` on lines [254][line-254] and [268][line-268]:

> Error C2131 expression did not evaluate to a constant (compiling source file C:\<stuff>\rapidcheck\src\detail\Testing.cpp)

I am building with `/Wall /W4 /WX /EHsc /wd4100 /wd4503 /wd4510 /wd4512 /wd4610 /MP`, but nothing else special. Any ideas as to what could be the problem?

[line-254]: https://github.com/emil-e/rapidcheck/blob/master/include/rapidcheck/detail/Variant.hpp#L254
[line-268]: https://github.com/emil-e/rapidcheck/blob/master/include/rapidcheck/detail/Variant.hpp#L268

**Comment by nikreiman** [comment]
Also worth noting: if I just remove the two functions in question, everything compiles fine. However I doubt that's the correct fix here. :)

**Comment by emil-e** [comment]
The "correct" fix is of course to use a better compiler but VS2015 is a supported target so the correct fix would be to make all of these jump tables `static const` instead of `constexpr`.
