### ISSUE TITLE
error: ‘const class boost::unit_test::test_case’ has no member named ‘full_name’

### ISSUE THREAD

**Issue by Christewart** [emil-e/rapidcheck#127]
I'm trying to add rapidcheck to my library. I've added the following headers to my file: 

```
#include <boost/test/unit_test.hpp>
#include <rapidcheck/boost_test.h>
```

The Boost version I am using is `1.59.0`, and I've tried using `1.61.0` as well. Both give this error

```
In file included from test/script_tests.cpp:31:0:
/home/chris/dev/rapidcheck/extras/boost_test/include/rapidcheck/boost_test.h: In function ‘void rc::detail::checkBoostTest(const string&, Testable&&)’:
/home/chris/dev/rapidcheck/extras/boost_test/include/rapidcheck/boost_test.h:14:26: error: ‘const class boost::unit_test::test_case’ has no member named ‘full_name’
   metadata.id = testCase.full_name();
                          ^
make[2]: *** [test/test_test_bitcoin-script_tests.o] Error 1
make[2]: Leaving directory `/home/chris/dev/bitcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/chris/dev/bitcoin/src'
make: *** [all-recursive] Error 1
```

**Comment by Christewart** [comment]
Is there a custom version of boost that needs to be used to interop with `rapidcheck`?

**Comment by emil-e** [comment]
That's very odd... RapidCheck CI builds against Boost 1.59.0 as you can see in the following script:
https://github.com/emil-e/rapidcheck/blob/master/ext/get_boost.sh

Can you try building the examples and use that script to get Boost just to see if it works then?

**Comment by Christewart** [comment]
I'll try doing that later today. Here is the file I was trying to use it in for the isuse I posted

https://github.com/Christewart/bitcoin/blob/rapidcheck/src/test/script_tests.cpp

The commit with all changes to add rapidcheck

https://github.com/Christewart/bitcoin/commit/f07879856cc0cb38dea3989f19f1d12df6f396b9

**Comment by Christewart** [comment]
So I tried building the examples, and here is the very first error I get: 

> In file included from /usr/include/c++/5/type_traits:35:0,
>                  from /home/chris/dev/rapidcheck/include/rapidcheck/Seq.h:3,
>                  from /home/chris/dev/rapidcheck/include/rapidcheck.h:7,
>                  from /home/chris/dev/rapidcheck/examples/counter/main.cpp:1:
> /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
>  #error This file requires compiler and library support for the \

which suggests that I don't have a C++11 compiler but I have G++ 5.3 (which from what I can tell is compliant) 

$ g++ --version
g++ (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> $ g++ --version
> g++ (Ubuntu 5.3.0-3ubuntu1~14.04) 5.3.0 20151204
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Is the Makefile not being built correctly? Shouldn't there be something like `g++ -std=c++11 ...`
in it?

Sorry, I'm not well versed at the C/C++ ecosystem

**Comment by Christewart** [comment]
So I managed to get the same error when running the `boost_test` example inside the `example` directory. 

```
chris@chris:~/.../examples/boost_test$ c++ -std=c++11 -I /usr/include/rapidcheck main.cpp
In file included from main.cpp:3:0:
/usr/include/rapidcheck/boost_test.h: In function ‘void rc::detail::checkBoostTest(const string&, Testable&&)’:
/usr/include/rapidcheck/boost_test.h:14:26: error: ‘const class boost::unit_test::test_case’ has no member named ‘full_name’
   metadata.id = testCase.full_name();
```

**Comment by emil-e** [comment]
Sorry for the late reply, was on vacation.

That's weird since it seems to build fine on Travis and I also used this version of Boost at work when using the Boost Test integration. I haven't had time to look at it myself, I'm afraid.

**Comment by Christewart** [comment]
It ended up being a version issue, I had two different versions of boost installed - one of them did not meet the minimum version requirements.
