### ISSUE TITLE
Advice on building gtest integration

### ISSUE THREAD

**Issue by NickJPavey** [emil-e/rapidcheck#145]
I'm a new user of RapidCheck, and so far I've been pretty impressed with the code you've made available. Thanks for all your work!

I've managed to build the library and run my first handful of tests, and now I'm looking to use the gtest integration. However, I'm having trouble getting it to build.

Before I describe my problem more fully, here's some basic system info:

OS : Ubuntu 14.04.5 LTS
CMake version : 2.8.12.2
Make version : 2.8.12.2
gcc version : gcc version 6.2.0 20160901

I'm using RapidCheck cloned from the following git SHA1 number:

> git rev-parse HEAD
> 6a065dded71788dd0e35c5003e0e1905d55336ae

The problem
-----------

I've read the documentation, in particular this statement:

> This support is available through the extras/gtest module. You
> can either directly add the extras/gtest/include directory to
> your include path or link against the rapidcheck_gtest target in
> your CMakeLists.txt. You can then simply #include
> <rapidcheck/gtest.h>. Note that rapidcheck/gtest.h needs to be
>included after gtest/gtest.h.

Unfortunately, I'm not very familiar with CMake, and wasn't able to put your advice into effect.

I started poking around inside the various CMakeLists.txt files, and found the following option that implies that it can be used to force the creation of the gtest integration library: RC_ENABLE_GTEST

I edited this option into the top-level CMakeLists.txt file, as follows:

> cmake_minimum_required(VERSION 2.8.12)
> project(rapidcheck)
> enable_testing()

> option(RC_ENABLE_GTEST "Build gtest integration" ON)
> option(RC_ENABLE_TESTS "Build RapidCheck tests" OFF)
> option(RC_ENABLE_EXAMPLES "Build RapidCheck examples" ON)

As you can see, I also enabled the building of the examples. Since at least one of them requires the gtest integration, I thought that may be another way of forcing the build.

When I ran the build as follows:

> cd /top/of/rapidcheck/checkout
> mkdir build
> cd build
> cmake ..

I got the following output:

> cmake ..
> -- The C compiler identification is GNU 6.2.0
> -- The CXX compiler identification is GNU 6.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Configuring done
> CMake Error at extras/gtest/CMakeLists.txt:1 (add_library):
>   Cannot find source file:

>     INTERFACE

>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx

Can you advise on the correct way of getting the gtest extensions to build? If you give an example, can you be as explicit as possible - my lack of experience with CMake is a bit of a hinderance.

Thanks very much,

Nick

**Comment by NickJPavey** [comment]
OK, I fixed this problem. It turns out that I had a problem with my link line which made it appear that the gtest integration symbols in RapidCheck hadn't been built.

For anyone else who's trying to use gtest alongside RapidCheck, with a conventional Makefile rather than CMake, here are some tips:

For your compile line, you'll need Make code that looks something like this:

```
INCLUDE_DIR_SWITCHES :=  -I <path to rapidcheck>/include -I <path to your other includes> -I <path to rapidcheck>/extras/gtest/include

%.o : %.cc Makefile
	g++ -g -O0 -Wall -Wextra -Werror $(INCLUDE_DIR_SWITCHES) -c $< -o $@ -Wno-shift-negative-value -Wno-unused-parameter
```

And your link line will need to look like:

```
LIBRARY_DIR_SWITCHES := -L <path to rapidcheck>/build -L <path to your other libraries> -L <another path to your other libraries>

LIBRARY_SWITCHES :=  -lgtest -l<your lib> -l<another lib> -l<etc> -lrapidcheck 


$(EXE_NAME) : main.o 
         g++ $^ $(LIBRARY_DIR_SWITCHES) $(LIBRARY_SWITCHES) -pthread -o $@

```
If you get garbage like this:


```
/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/main.cc:383: undefined reference to `testing::InitGoogleTest(int*, char**)'
main.o: In function `__static_initialization_and_destruction_0':
/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/main.cc:344: undefined reference to `testing::internal::GetTestTypeId()'
/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/main.cc:344: undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
main.o: In function `RUN_ALL_TESTS()':
/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/../../../../common/include/gtest/gtest.h:2288: undefined reference to `testing::UnitTest::GetInstance()'

<snip>

/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/../../testing_frameworks/rapidcheck/include/rapidcheck/Assertions.hpp:35: undefined reference to `rc::detail::makeExpressionMessage(std::string const&, int, std::string const&, std::string const&)'
/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/../../testing_frameworks/rapidcheck/include/rapidcheck/Assertions.hpp:35: undefined reference to `rc::detail::CaseResult::CaseResult(rc::detail::CaseResult::Type, std::string)'
main.o: In function `void rc::detail::doAssert<rc::detail::expr::GT<rc::detail::expr::Value<int>, int> >(rc::detail::expr::GT<rc::detail::expr::Value<int>, int> const&, bool, rc::detail::CaseResult::Type, std::string const&, int, std::string const&)':
/home/npavey/Work/Mapper_Hardening/mapDispatcher_refactor/mapMessagesLowLevelMaps/mapperHardeningTestTools/rapidCheckTests/get_permutation_1/../../testing_frameworks/rapidcheck/include/rapidcheck/Assertions.hpp:35: undefined reference to `rc::detail::makeExpressionMessage(std::string const&, int, std::string const&, std::string const&)'

<snip>

```
It's because the ordering of the object files and libraries on the link line is incorrect.

The '.o' files you build from your own .c/.cc/.cpp files need to come before the libraries.

Modern GCC toolchains (like those needed for c++11 support) are more strict about the ordering of object files and libraries, so this might be something to watch out for.

**Comment by emil-e** [comment]
Glad you got it working!
