### ISSUE TITLE
Build issue when compiling Container.hpp

### ISSUE THREAD

**Issue by neilzxu** [emil-e/rapidcheck#148]
Getting the following error when trying to compile with the CMake:

`/home/zxu131/rapidcheck/include/rapidcheck/gen/Container.hpp:491:42: note:         ‘gens’
/home/zxu131/rapidcheck/include/rapidcheck/gen/Container.hpp:491:46: error: expansion pattern ‘gens’ contains no argument packs
     return helper.generate(random, size, gens...);`

I've pulled/initialized/update all the submodules if that matters.

**Comment by emil-e** [comment]
What compiler are you using?

**Comment by neilzxu** [comment]
gcc 4.8.4. Seems like it was the result of a [documented compiler bug with variadic templates inside anonymous lambda functions](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41933).
