### ISSUE TITLE
Can't print custom values in namespaces.

### ISSUE THREAD

**Issue by Timmmm** [emil-e/rapidcheck#151]
Check this out:

```
namespace NS {
struct Foo // Just some class in a namespace.
{
    explicit Foo(int a) : x(a) {}
    int x = 0;
};
}

using NS::Foo;

namespace rc {
template<>
struct Arbitrary<Foo>
{
    static Gen<Foo> arbitrary()
    {
        return gen::construct<Foo>(gen::arbitrary<int>());
    }
};
}

void showValue(const Foo& foo, std::ostream& os) {
    os << "foo: " << foo.x;
}

RC_GTEST_PROP(Show, Show, (const Foo& f))
{
    RC_ASSERT(false);
}
```

This prints:

```
Failed
Falsifiable after 1 tests

std::tuple<NS::Foo>:
(<???>)
```

If you remove the NS namespace it works fine. This is beyond my C++ template knowledge. Is there a way to make this work or is it simply impossible to print custom values that are in namespaces?

**Comment by emil-e** [comment]
For ADL (argument dependent lookup) to find your custom print function, it needs to be in the same namespace as the type it is printing. In this case `NS`.

**Comment by Timmmm** [comment]
Aha that works, thanks! I know there'd be some obscure lookup rule...

It'd be nice if there were a file in `/docs` about showing custom values. Maybe something like this:

> # Displaying Custom Types
> 
> If you find that RapidCheck is printing `<???>` for your custom types then you can add support for printing them correctly. RapidCheck checks two ways of printing the value:
> 
> 1. Is there a function `void showValue(const T& value, std::ostream& os)` for your type `T`?
> 2. If not, does it provide an overload of `std::ostream& operator<<(std::ostream& os, const T& value)`?
> 
> If neither of those are true then it prints `<???>`.
> 
> For example, consider a simple vector struct:
> 
>     struct Vector
>     {
>         float x, y, z;
>     };
> 
> You can add custom printing by implementing `showValue()` as follows:
> 
>     void showValue(const Vector& v, std::ostream& os)
>     {
>         os << "[" << v.x << ", " << v.y << ", " << v.z << "]";
>     }
> 
> Note that for the argument dependent lookup to work, `showValue()` must be in the same namespace as `Vector`, otherwise it will be ignored.
