### ISSUE TITLE
GTest CMake broken under CMake 2.8

### ISSUE THREAD

**Issue by jeremysalwen** [emil-e/rapidcheck#163]
extras/gtest/CMakeLists.txt fails with 

```
CMake Error at rapidcheck/extras/gtest/CMakeLists.txt:2 (add_library):     
  Cannot find source file:   
         INTERFACE
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx     
```
This is a caused by the using the "INTERFACE" feature which is not available in CMake 2.8.12.  However, the CMakeLists.txt in the root declares a minimum version of CMake 2.8.12.

**Comment by emil-e** [comment]
Do you happen to know when this was added?

**Comment by janisozaur** [comment]
It surely is present in 3.0: https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#interface-libraries

CMake's online docs only go that far, but it's likely 2.8 was the last major release before 3.0

**Comment by janisozaur** [comment]
Indeed: https://cmake.org/files/ and https://gitlab.kitware.com/cmake/cmake/tags?page=4&sort=updated_desc confirm it was 2.8.12, then 3.0
