### ISSUE TITLE
check assertion which requires two vectors of the same size

### ISSUE THREAD

**Issue by greg7mdp** [emil-e/rapidcheck#195]
I can have an assertion that takes two vectors and that checks that they are the same size with RC_PRE, but then rapidcheck gives up after a few tests.

There should be a better way of doing this, probably have an assertion that takes one vector, and then generates a second random vector of the same size, but I can't figure out how to do this:

```
    rc::check([](const std::vector<int> &bv1) {
              const std::vector<int> bv2 = ???
```

Any suggestion?

Thanks!

**Comment by greg7mdp** [comment]
Never mind, I found a way with `Gen<Container> container(std::size_t count, Gen<Ts>... gens)`.
rapidcheck is amazingly great, even though I have a hard time understanding the source code. Truly impressive!

**Comment by emil-e** [comment]
👍
