### ISSUE TITLE
Generating a union type with varying type based on the union

### ISSUE THREAD

**Issue by hillsprig** [emil-e/rapidcheck#197]
Is it possible to generate a type, which will be used to identify a specific union or payload contents, and then invoke the specific generator for that type?

There's a small example below, but running into problems because mapcat expects a certain specific type only. Not sure how to templatize this if possible.

Any ideas how to generate something like that?

Thank you!

Small pseudo example:

```
struct Apple {
 uint32_t yumyum;
}

struct Banana {
 uint8_t stalk;
 uint8_t skin;
 uint8_t core;
 uint8_t seed;
}


struct Cherry {
 uint32_t stem;
 uint32_t fruityParts;
}

struct Fruit {
 fruitType type;
 union {
  Apple apple;
  Banana banana;
  Cherry cherry;
 };
}

const auto fruit = *gen::mapcat(gen::arbitrary<fruitType>(), [](fruitType type) {
    if (type == APPLE)
        return gen::arbitrary<Apple>();
    else if (type == BANANA)
        return gen::arbitrary<Banana>();
    else if (type == CHERRY)
        return gen::arbitrary<Cherry>();
});
```

**Comment by kfish** [comment]
Hi, I'm not how to implement this without hand-rolling a generator for `Fruit`. Here's a version using `std::variant` (requires C++17, or equivalently you could use `boost::variant`):

```c++
#include <variant>                                                                 

struct Apple {                                                                     
 uint32_t yumyum;
};                                                                                 

struct Banana {
 uint8_t stalk;                                                                    
 uint8_t skin;
 uint8_t core;
 uint8_t seed;                                                                     
};  

struct Cherry {
 uint32_t stem;
 uint32_t fruityParts;                                                             
}; 

using Fruit = std::variant<Apple, Banana, Cherry>;
```

First you need generators for your base types (not sure if this can be derived automatically?), and for `std::variant`:

```c++

template <>
struct Arbitrary<Apple> {
    static Gen<Apple> arbitrary() {
        return gen::build<Apple>(
            gen::set(&Apple::yumyum));
    }
};

template <>
struct Arbitrary<Banana> {
    static Gen<Banana> arbitrary() {
        return gen::build<Banana>(
            gen::set(&Banana::stalk),
            gen::set(&Banana::skin),
            gen::set(&Banana::core),
            gen::set(&Banana::seed));
    }
};

template <>
struct Arbitrary<Cherry> {
    static Gen<Cherry> arbitrary() {
        return gen::build<Cherry>(
            gen::set(&Cherry::stem),
            gen::set(&Cherry::fruityParts));
    }
};

template <typename T, typename... Ts>
struct Arbitrary<std::variant<T, Ts...>> {
    static Gen<std::variant<T, Ts...>> arbitrary() {
        return gen::oneOf(
            gen::cast<std::variant<T, Ts...>>(gen::arbitrary<T>()),
            gen::cast<std::variant<T, Ts...>>(gen::arbitrary<Ts>())...);
    }
};
```

At this point we can verify the generator works:

```c++
RC_BOOST_PROP(check_compilation, (Fruit fruit)) {
    RC_ASSERT(true);
}
```

To actually do a useful check, we need a visitor on the variant type (see https://en.cppreference.com/w/cpp/utility/variant/visit):

```c++
template<class... Ts> struct overloaded : Ts... { using Ts::operator()...; };
template<class... Ts> overloaded(Ts...) -> overloaded<Ts...>;

RC_BOOST_PROP(check_fruit, (Fruit fruit)) {
    RC_ASSERT(std::visit(overloaded {
        [](Apple apple) { return apple.yumyum > 0; },
        [](Banana banana) { return banana.stalk < banana.core; },
        [](Cherry cherry) { return cherry.stem > 2 * cherry.fruityParts; },
    }, fruit));
}
```

For completeness, here's a generator for `std::monostate`, which you need in your variant type if the base types are not default-constructible:
```c++
template<>
struct Arbitrary<std::monostate> {
    static Gen<std::monostate> arbitrary() {
        return gen::element(std::monostate());
    }   
};
```

**Comment by hillsprig** [comment]
Hi kfish,

Thank you very much for the detailed reply. I got it all building as is, and would like to thank you for that especially as I have been struggling with template complication errors several times in my own experiments :) This will definitely come a long way to solve the use-case I am working on.

Now just to convince the people here to let me use boost (ruling out the possibility that they'd dare let me use a new enough compiler for C++17).

Again, thank you for the clean and elegant example, and also the extra tidbits like the overloaded templates and monostate, they will be useful here and in other places :)

Thank you.
