### ISSUE TITLE
Using resize with arbitrary<int> generators

### ISSUE THREAD

**Issue by KingDuckZ** [emil-e/rapidcheck#203]
I'm having troubles trying to restrict the range of ints generated by rapidcheck. In my test case I want to have values between -500 and 500.

In the documentation I found:

> [Size] When generating primitive integral types, the size controls the maximum values that can be generated.

and

> Gen<T> resize(int size, Gen<T> gen)
>
> Returns a version of the given generator that always uses the specified size.
> 
> ```
> // Example:
> const auto fullRangeInt = *gen::resize(kNominalSize, gen::arbitrary<int>());
> ```

In my code I did:

```
const auto int_gen = resize(rc::kNominalSize, arbitrary<int>()).as("from-to range");
const int n1 = *int_gen;
const int n2 = *int_gen;
std::cout << "testing n1 = " << n1 << ", n2 = " << n2 << '\n';
```

The values I get look like these:

Using configuration: seed=15587643132008837968

- numbers in range should match with counter's
testing n1 = -696116925, n2 = -2007727547
testing n1 = -696116925, n2 = -2007727547
testing n1 = 0, n2 = -2007727547
testing n1 = 0, n2 = -2007727547
testing n1 = 0, n2 = 0
testing n1 = 0, n2 = 2007727547
testing n1 = 0, n2 = 2007727547
testing n1 = 0, n2 = 0

so very little to do with the 100 I pass in. Following the code (probably to the wrong place) I figured out that size might be some kind of bit size, following the formula (size * sizeof(int) * CHAR_BIT + (kNominalSize / 2) / kNominalSize. I can't make any sense out of that either, and using size = 8, 9 or 10 just yields very small values.
Am I doing something wrong? Am I misinterpreting the documentation?

**Comment by emil-e** [comment]
What you want is ´gen::inRange`:
https://github.com/emil-e/rapidcheck/blob/master/doc/generators_ref.md#gent-inranget-min-t-max
