### ISSUE TITLE
Marking specific tests as pure functions?

### ISSUE THREAD

**Issue by CapacitorSet** [emil-e/rapidcheck#229]
I see that RapidCheck will sometimes try the same inputs more than once, eg. the first testcase will repeat the zero-input a few times, and failing testcases will also repeat the failing input a few times. It could be interesting if the user could mark a test as a pure function (one whose output doesn't change if the input doesn't change), so that more testcases could be explored and the shrinking process could take fewer iterations.

**Comment by emil-e** [comment]
A test being a pure function is already an absolute requirement for RapidCheck to work at all so there's no reason to mark anything, RapidCheck already assumes it. Regarding deduplication of test cases, that would require values to be comparable for equality. Not all values satisfy this and having compile time switching for this would introduce complexity. However, it's perfectly reasonable and possible for individual generators to test for this and try to avoid it.
