### ISSUE TITLE
Make RTTI enable default consistent between headers and library compile

### ISSUE THREAD

**Issue by tsmanner** [emil-e/rapidcheck#267]
## Problem
A default build and install of `rapidcheck` builds the library with RTTI enabled.
The headers in `rapidcheck/include` have RTTI disabled by default.

## Symptom
Including the headers from `rapidcheck/include` in a compile that is linking against a default compile of `rapidcheck.a` results in SIGSEGV failures when an `RC_ASSERT` macro fails it's condition.

## Expected Behavior
A default compile of `rapidcheck` should be usable by default with it's includes.

## Suggested Solution(s)
1. Invert the `RC_USE_RTTI` define by changing it to `RC_DONT_USE_RTTI`, replace the `#ifdef`s with `#ifndef`s, and update the `CMakeLists.txt` to set `RC_DONT_USE_RTTI` if `NOT RC_ENABLE_RTTI`.
2. Change the default setting for `RC_USE_RTTI` to `OFF` in the `CMakeLists.txt`.

**Comment by cqc-alec** [comment]
See also https://github.com/emil-e/rapidcheck/issues/246

**Comment by tsmanner** [comment]
@cqc-alec Yeah, I read that a couple of days ago.  IMO users of a library shouldn't need to crawl through the issues page to learn that it will fail with it's default settings when used in a normal way.

**Comment by cqc-alec** [comment]
@tsmanner Yeah as someone who was bitten by this I agree with you.

**Comment by emil-e** [comment]
Apologize for the inconvenience, this might have happened through some PR that I merged. I never added support myself for non-RTTI builds.

**Comment by emil-e** [comment]
Thanks for the PR, I don’t have that much time myself these days. I’m closing this since it’s merged.

**Comment by tsmanner** [comment]
No worries, it only seems to happen when optimizations or stripped binaries are involved.  I ran in to it when doing some builds in `nixpkgs`, which is currently pinned to an old version.  Pointing to newer versions caused the segfault because it strips the binaries when installing them.  My use case is a little obscure 😂 so I appreciate you taking a look.  Also, for having written this in the first place!
