### ISSUE TITLE
Updating googletest dependencies to account for inclusive language

### ISSUE THREAD

**Issue by messerb5467** [emil-e/rapidcheck#291]
With moves towards inclusive language:
https://www.ibm.com/blogs/think/2020/08/words-matter-driving-thoughtful-change-toward-inclusive-language-in-technology/
we'd like to see the version of google test used in rapid check updated to remove "whitelist" and "blacklist" terms from the overall dependency hierarchy.

It is understood that this is a big ask and there is no expectation or rush to completion on something like this. Please feel free to go through the repository's natural versioning cycles to complete such an ask.

Thanks again for the hard work and I really appreciate the acceptance of the prior PR.

**Comment by messerb5467** [comment]
@emil-e Do you have any thoughts on the above?

**Comment by emil-e** [comment]
@messerb5467 I'm not aware of anyone, I'm afraid. I do get pull requests every now and then that I try to merge when I have the time to look through them. For what it's worth, it's not a very difficult change most likely, but I can't really say without looking at what the upstream changes to Google Test are.

**Comment by messerb5467** [comment]
@emil-e ok. we're going to take a crack at updating it. Is there anything I need to know about running the unit tests?
