### ISSUE TITLE
Errors with 32 bit compiles

### ISSUE THREAD

**Issue by fire** [emil-e/rapidcheck#74]
With MSVC, if you compile the project in win32 mode, it errors with several warnings. Is this a supported build? I did not notice appveyor testing this.

**Comment by emil-e** [comment]
This is not tested by AppVeyor but it should definitely be supported. Thanks for reporting and I will definitely look into this ASAP.

**Comment by emil-e** [comment]
@fire: This is now fixed on master. I've added a 32-bit build configuration to AppVeyor.

**Comment by fire** [comment]
Thanks, someone needs to use this with 32bit code, but hopefully it'll work.

**Comment by emil-e** [comment]
@fire I see no specific reason it should not work since all the tests are passing but there can always be bugs of course. Please report any bugs you find and I'll prioritize fixing them.
